
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-container:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - uses: docker/build-push-actions/checkout@v4
     -run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
     -with:
        username: ${{ github.actor }}
        password: ${{ secrets.github_TOKEN }}
        regisrty: docker.pkg.github.com
        repository: ${{ github.repository }}/next
        tags : latest, ${{ github.run_number }}
    - name: publish to Docker Hub
      uses: docker/build-push-actions/checkout@v4
      with:
        username: ${{ secrets.Docker_USERNAME }}
        password: ${{ secrets.Docker_PASSWORD }}
        repository: seesharprun/next
        tags: latest, ${{ github.run_number }}
